### ISSUE TITLE
Fuzzing: Attempt to add with overflow and/or invalid ArrayVec::set_len

### ISSUE THREAD

**Issue by saethlin** [paolobarbolini/bzip2-rs#1]
I'm attaching the full original reproducer, which crashes at:
```
thread '<unnamed>' panicked at 'attempt to add with overflow', /home/ben/bzip2-rs/src/block/mod.rs:255:17
```
It appears to minimize into a different crash, which is very interesting. You should be able to `tar xf` this file in the crate root and get a file in `fuzz/artifacts/decompress`:
[crash-14f4cbb67ac1b1daa7493646937fe87be63f72e1.tar.gz](https://github.com/paolobarbolini/bzip2-rs/files/5900413/crash-14f4cbb67ac1b1daa7493646937fe87be63f72e1.tar.gz)

**Comment by paolobarbolini** [comment]
Thanks for taking the time in fuzzing this project!

It looks like a `checked_add` should catch this issue. I'll take a look at it tomorrow.
